version: "2"

services:
  myapp:
    container_name: node-app
    image: michael/node-app
    build: .
    command: nodemon --debug=5858
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8080:8080"
      - "5858:5858"
