version: "2"

services:
  myapp:
    container_name: node-app
    image: michael/node-app
    build: .
    command: nodemon --debug=5858
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
      - "5858:5858"
