version: "2"

services:
  myapp:
    container_name: node-app
    image: michael/node-app
    build: .
    # command: nodemon --debug=5858
    command: npm start && run watch
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
      - "5858:5858"
  db:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27018:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
