export const REQUEST_SERVER_ERROR = 'REQUEST_SERVER_ERROR';
export const LOAD_ISSUES_SUCCESS = 'LOAD_ISSUES_SUCCESS';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';
