export const REQUEST_ISSUES = 'REQUEST_ISSUES'
export const REQUEST_ISSUES_LOADING = 'REQUEST_ISSUES_LOADING'
export const REQUEST_ISSUES_ERROR = 'REQUEST_ISSUES_ERROR'
export const REQUEST_ISSUES_SUCCESS = 'REQUEST_ISSUES_SUCCESS'

export const ADD_ISSUE = 'ADD_ISSUE'
